[package]
name = "tibco_ems"
version = "0.2.10"
authors = ["Jens Walter <jens@apimeister.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tibco","ems"]
repository = "https://github.com/apimeister/tibco-ems-rs/"
description = "A high level API for the Tibco EMS."

[dependencies]
log = "0.4"
tibco_ems-sys = "0.1.12"
serde = { version = "1", features = ["derive"] }
bincode = "1"

[dev-dependencies]
env_logger = "0.8"